### ISSUE TITLE
Beginner tasks?

### ISSUE THREAD

**Issue by kanishka-work** [zkcrypto/bellman#28]
I'll leave this open as a combination of tasks that people getting familiar with rust, zk-snarks, and bellman specifically can do to become proficient contributors to this codebase. Please respond or edit the list below.

- [ ] ....

I'll try to attempt some of the items mentioned as I get time. Hopefully other newbies to this codebase will also find this useful.

**Comment by vaibhavchellani** [comment]
@kanishka-azimi anything on your mind for a newbie ?

**Comment by kanishka-azimi** [comment]
I didn't dig into the code yet. Maybe others can list out items they have in mind.
