### ISSUE TITLE
Implement batched Groth16 verification

### ISSUE THREAD

**Issue by daira** [zkcrypto/bellman#31]
Appendix B.2 of the Zcash protocol spec describes how to do batched verification. The Zcash ticket is https://github.com/zcash/zcash/issues/320 .

[Note that bellman can just provide batched and unbatched verification as separate APIs. We don't need to bikeshed here about how these will be used to implement Zcash consensus policy, as happened on the [PR to add batched PHGR13 verification to libsnark](https://github.com/zcash/libsnark/pull/9); please keep that to the Zcash ticket.]

**Comment by str4d** [comment]
@hdevalence has a proposal for the `bellman` batching API in https://github.com/zcash/librustzcash/issues/253

**Comment by str4d** [comment]
This was implemented in #59.
