### ISSUE TITLE
What to expect from: "expected more bases from source"

### ISSUE THREAD

**Issue by drewstone** [zkcrypto/bellman#35]
Hello,

I'm working on a _simple_ merkle tree snark. I have printed logs to ensure that my circuit is working, but it seems to fail with this error before returning the proof. I'm unsure how to proceed as I'm following examples around the web that seem to work as well. Any ideas why I'm getting this error.

It occurs here: https://github.com/drewstone/rust-miximus/blob/master/src/zk_util.rs#L107
The unwrap fails with exactly this error:
```
thread 'test::test_generate_params' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Custom { kind: UnexpectedEof, error: StringError("expected more bases from source") })', src/libcore/result.rs:997:5
```

**Comment by kobigurk** [comment]
For reference, this error was the result of not enough powers of tau in the CRS. That's because the merkle tree in generation phase contained 0 levels and in the proving phase contained >0 levels.

**Comment by drewstone** [comment]
Thanks @kobigurk
