### ISSUE TITLE
no_std support in the future?

### ISSUE THREAD

**Issue by drewstone** [zkcrypto/bellman#42]
Any chance this is in the pipeline?

**Comment by fubuloubu** [comment]
We've had luck running proving systems with `no_std`. You can't do generation (and probably shouldn't find a workaround either) but you can workaround the RNG with proving by having a seedable RNG (such as `XorShiftRng::from_seed(seed)`) and passing in an external seed.

I don't have a public example for you, but this should help if you're still having issues.
